version: '3'
service:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    dependends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postres
    volumes:
      - pgdatevol:/var/lib/postgresql/date
volumes:
  pgdatavol:
